### ISSUE TITLE
gulp build errors

### ISSUE THREAD

**Issue by johnjamesjacoby** [nolimits4web/Framework7#391]
```
$: gulp build
[18:37:17] Using gulpfile /www/framework7/gulpfile.js
[18:37:17] Starting 'scripts'...
[18:37:17] Starting 'styles'...
[18:37:17] Starting 'demo-app'...
[18:37:17] Finished 'demo-app' after 6.07 ms
/www/framework7/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/www/framework7/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/www/framework7/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/www/framework7/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/www/framework7/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/www/framework7/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/www/framework7/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/www/framework7/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/www/framework7/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/www/framework7/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
```

* Node v0.12.0
* gulp Local & CLI version 3.8.11
* Tried wiping out the `node_modules` directory and starting over, no joy.
* I have a hunch this is a dependency issue, but posting here incase someone else runs into it.

**Comment by nolimits4web** [comment]
I have Node 0.10.26 and same Gulp and everything fine for me. Will investigate it

**Comment by nolimits4web** [comment]
By the way, it seems like gulp-less updated today 3.0.0, can you try to update your local dep and try it again (in package.json it is 2.0.x)

**Comment by nolimits4web** [comment]
Just checked, updated my Node to 0.12 and reinstalled global gulp to latest 3.8.11. Build works fine without issues

**Comment by johnjamesjacoby** [comment]
Confirmed fixed. Closing.
